browsersync:
  notify: true
  open:   false
  port:   3000
  server:
    basedir: "_site/"
  xip:    true

clean:
  # The jekyll build dir
  - "_site"

copy:
  # Paths to static assets that aren't (S)CSS or JavaScript
  # because these are completely handled by the sass and javascript tasks
  assets:
    # all files below the _assets dir
    - "_assets/**/*"
    # exclusions:
    - "!_assets/{js,scss,css}/**/*"   # js, scss and css files
    - "!_assets/css{,/**}"            # css dir
    - "!_assets/js{,/**}"             # js dir
    - "!_assets/scss{,/**}"           # scss dir
    - "!_assets/vendor{,/**}"         # vendor dir
  dist: "_site/assets/"
  notification: "Running Copy"

javascript:
  dest:
    jekyllRoot: "_assets/js/"
    buildDir: "_site/assets/js/"
  # filename to output
  filename: "all.js"
  notification: "Running JavaScript"
  # Paths to JavaScript libraries, which are combined into one file
  src:
    # Libraries requried by Foundation
    - "_assets/vendor/jquery/dist/jquery.js"
    - "_assets/vendor/what-input/what-input.js"

    # Core Foundation files, all Foundation components need this!
    - "_assets/vendor/foundation-sites/js/foundation.core.js"

    # Individual Foundation components
    # If you aren't using a component, just remove it from the list
    # - "_assets/vendor/foundation-sites/js/foundation.abide.js"
    # - "_assets/vendor/foundation-sites/js/foundation.accordion.js"
    # - "_assets/vendor/foundation-sites/js/foundation.accordionMenu.js"
    # - "_assets/vendor/foundation-sites/js/foundation.drilldown.js"
    # - "_assets/vendor/foundation-sites/js/foundation.dropdown.js"
    # - "_assets/vendor/foundation-sites/js/foundation.dropdownMenu.js"
    # - "_assets/vendor/foundation-sites/js/foundation.equalizer.js"
    # - "_assets/vendor/foundation-sites/js/foundation.interchange.js"
    # - "_assets/vendor/foundation-sites/js/foundation.magellan.js"
    # - "_assets/vendor/foundation-sites/js/foundation.offcanvas.js"
    # - "_assets/vendor/foundation-sites/js/foundation.orbit.js"
    # - "_assets/vendor/foundation-sites/js/foundation.responsiveMenu.js"
    # - "_assets/vendor/foundation-sites/js/foundation.responsiveToggle.js"
    # - "_assets/vendor/foundation-sites/js/foundation.reveal.js"
    # - "_assets/vendor/foundation-sites/js/foundation.slider.js"
    # - "_assets/vendor/foundation-sites/js/foundation.sticky.js"
    # - "_assets/vendor/foundation-sites/js/foundation.tabs.js"
    # - "_assets/vendor/foundation-sites/js/foundation.toggler.js"
    # - "_assets/vendor/foundation-sites/js/foundation.tooltip.js"
    # - "_assets/vendor/foundation-sites/js/foundation.util.box.js"
    # - "_assets/vendor/foundation-sites/js/foundation.util.keyboard.js"
    # - "_assets/vendor/foundation-sites/js/foundation.util.mediaQuery.js"
    # - "_assets/vendor/foundation-sites/js/foundation.util.motion.js"
    # - "_assets/vendor/foundation-sites/js/foundation.util.nest.js"
    # - "_assets/vendor/foundation-sites/js/foundation.util.timerAndImageLoader.js"
    # - "_assets/vendor/foundation-sites/js/foundation.util.touch.js"
    # - "_assets/vendor/foundation-sites/js/foundation.util.triggers.js"

    # Paths to your own project code are here
    # All the files in this list and in the js dir are concatenated into all.js
    - "!_assets/js/all.js"
    - "_assets/js/*.js"

jekyll:
  notification: "Running jekyll"

revision:
  revision:
    dest: "_site/assets"
    manifest:
      dest: "./"
    src:
      - "_assets/css/app.css"
      - "_assets/js/all.js"
      - "_assets/img/**"
  collect:
    dest: "_site"
    src:
      - "./rev-manifest.json"
      - "_site/*.{html,xml,txt,json,css,js}"
      - "_site/**/*.{html,xml,txt,json,css,js}"
      - "!_site/assets/vendor"

sass:
  # Autoprefixer will make sure your CSS works with these browsers
  compatibility:
    - "last 2 versions"
    - "ie >= 9"
  dest:
    jekyllRoot: "_assets/css/"
    buildDir: "_site/assets/css/"
  notification: "Running Sass"
  src: "_assets/scss/*.scss"

watch:
  images: "_assets/img/**/*"
  javascript: "_assets/js/app.js"
  sass: "_assets/scss/**/*.scss"
  pages:
    - "*.{md,html,yml,xml}"
    - "{_data,_includes,_layouts,_pages,_posts}/**/*.{md,html,yml,xml}"
    - "!_site/**/*.*"
    - "!_assets/**/*.*"
